credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$kOhDMjVmP5CTaByYEexG4OIMyPknVsxLHKdlltN8NBtKZ.kCNEZz. # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: '$2b$12$N7.rbdBYKsAcs9rquwjdXuTCKOAybBq.AOcWjzXGEWDkDI.zkJ8mK' # To be replaced with hashed password
    amit:
      email: amit@gmail.com
      name: Amit
      password: '$2b$12$jbzcBaN0cP4qTnjUDgHhPeyHp2.lOG523ddgy3/rhTl/obpvcZwgu'
    youssef:
      email: youssef@gmail.com
      name: youssef
      password: '$2b$12$MZnfLkRzpk3WyMl6lq25Vuu8wEyODLWHSm1HcxlpeAbarHUvIYGFa'
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com